import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{ADDRESS,EX,connect,read,wait,write}from'./genlayer.js';import'./style.css';import'./proof.css';
const short=v=>v?`${String(v).slice(0,8)}…${String(v).slice(-6)}`:'—';const n=v=>Number(v?.toString?.()??v??0);
function App(){const[wallet,setWallet]=useState(null),[cfg,setCfg]=useState(null),[chain,setChain]=useState('SEPOLIA'),[hash,setHash]=useState(''),[policy,setPolicy]=useState('ROUTINE_OPERATIONS'),[id,setId]=useState('1'),[record,setRecord]=useState(null),[calls,setCalls]=useState([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState('Load an existing certificate or connect any wallet to analyze a Safe transaction.');
 useEffect(()=>{if(ADDRESS)read('get_config').then(setCfg).catch(e=>setNotice(e.message))},[]);
 const load=async(value=id)=>{setBusy(true);try{const r=await read('get_assessment',[Number(value)]);setRecord(r);setCalls(JSON.parse(r.calls_json||'[]'));setNotice(`Certificate #${value} synchronized from contract.`)}catch(e){setRecord(null);setCalls([]);setNotice(e.message)}finally{setBusy(false)}};
 const analyze=async()=>{if(!wallet)return setNotice('Connect a wallet first.');setBusy(true);try{const tx=await write(wallet,[chain,hash.trim(),policy]);setNotice(`Submitted ${short(tx)}. Waiting for consensus…`);await wait(tx,s=>setNotice(`${short(tx)} · ${s.label}`));const latest=await read('get_config');setCfg(latest);const next=String(latest.assessment_count);setId(next);await load(next);setNotice(`Finalized, executed successfully, and certificate #${next} read back.`)}catch(e){setNotice(e.message)}finally{setBusy(false)}};
 const tone=useMemo(()=>record?.state?.toLowerCase()||'idle',[record]);
 return <><header><div className="brand"><img src="/safe-call-logo.png"/><div><b>SafeCall Firewall</b><span>Multisig transaction scope auditor</span></div></div><nav><a href="#analyze">Analyze</a><a href="#how">How it works</a><a href="https://docs.safe.global/core-api/transaction-service-overview" target="_blank">Safe source ↗</a></nav><button className="connect" onClick={async()=>{try{setWallet(await connect());setNotice('Wallet connected. Every wallet has equal access.')}catch(e){setNotice(e.message)}}}>{wallet?short(wallet.account):'Connect wallet'}</button></header>
 <main><section className="hero"><div><span className="eyebrow">GENLAYER · STUDIONET</span><h1>See the calls.<br/><em>Gate the risk.</em></h1><p>Turn one official Safe transaction record into an immutable call-graph certificate. No admin wallet. No user-supplied evidence URL.</p><div className="stats"><span><b>{cfg?n(cfg.assessment_count):'—'}</b> certificates</span><span><b>5</b> fixed chains</span><span><b>3</b> closed policies</span></div></div><img className="hero-logo" src="/safe-call-logo.png"/></section>
 <section className="workspace" id="analyze"><article className="locator"><div className="kicker">01 · TRANSACTION LOCATOR</div><h2>Inspect a Safe proposal</h2><label>Safe network<select value={chain} onChange={e=>setChain(e.target.value)}>{['ETHEREUM','SEPOLIA','OPTIMISM','ARBITRUM','BASE'].map(x=><option key={x}>{x}</option>)}</select></label><label>Safe transaction hash<textarea value={hash} onChange={e=>setHash(e.target.value)} placeholder="0x… 32-byte safeTxHash"/></label><label>Risk policy<select value={policy} onChange={e=>setPolicy(e.target.value)}>{['STRICT_NO_ADMIN','ROUTINE_OPERATIONS','TREASURY_REVIEW'].map(x=><option key={x}>{x}</option>)}</select></label><button className="primary" disabled={busy||!wallet||hash.length!==66} onClick={analyze}>{busy?'Processing…':'Analyze on GenLayer'}</button><small>Any connected wallet can analyze. The deployer has no runtime privilege.</small><div className="load"><input value={id} onChange={e=>setId(e.target.value)} placeholder="Certificate ID"/><button disabled={busy} onClick={()=>load()}>Load</button></div></article>
 <article className="graph"><div className="graph-head"><div><div className="kicker">02 · EXPLODED CALL GRAPH</div><h2>{record?`Certificate #${id}`:'Awaiting certificate'}</h2></div><span className={`verdict ${tone}`}>{record?.state||'NO DATA'}</span></div>{record?<><div className="envelope"><div><small>Safe</small><b>{short(record.safe_address)}</b></div><i>→</i><div><small>Target</small><b>{short(record.target)}</b></div><i>→</i><div><small>Operation</small><b>{n(record.operation)===1?'DELEGATECALL':'CALL'}</b></div></div><div className="call-list">{calls.length?calls.map((c,i)=><div className={`call ${String(c.risk).toLowerCase()}`} key={i}><span>{String(i+1).padStart(2,'0')}</span><div><b>{c.method}</b><small>{short(c.target)} · {c.category}</small></div><mark>{c.risk}</mark></div>):<div className="empty">No decoded leaf calls were certified.</div>}</div><div className="summary"><b>{record.reason}</b><p>{record.summary||'No semantic summary available.'}</p></div><div className="certificate-proof"><div><small>Leaf metrics</small><b>{n(record.blocked_call_count)} blocked · {n(record.review_call_count)} review · {n(record.unknown_call_count)} unknown</b></div><div><small>Policy commitment</small><b title={record.policy_digest}>{short(record.policy_digest)}</b></div><div><small>Call graph commitment</small><b title={record.call_graph_digest}>{short(record.call_graph_digest)}</b></div><div><small>Certificate commitment</small><b title={record.certificate_digest}>{short(record.certificate_digest)}</b></div></div></>:<div className="empty large">Enter a Safe transaction hash and connect any wallet, or load a prior certificate ID.</div>}</article></section>
 <section className="proof"><div className="kicker">03 · PROOF BOUNDARY</div><div className="proof-grid"><article><b>Authority</b><p>Contract-built Safe Transaction Service endpoint for the selected chain.</p></article><article><b>Binding</b><p>Exact safeTxHash, Safe, nonce, target, operation and fetched-content digests.</p></article><article><b>Judgment</b><p>Validators classify every decoded leaf; deterministic policy produces the state.</p></article><article><b>Not claimed</b><p>No guarantee of economic safety, signer authorization or future execution.</p></article></div></section>
 <section className="how" id="how"><div className="kicker">04 · HOW IT WORKS</div><h2>A permissionless reviewer path</h2><div className="steps">{[['1','Connect','Use any StudioNet-compatible wallet. There are no owner roles or constructor allowlists.'],['2','Locate','Select a supported chain and paste an exact Safe transaction hash—not an arbitrary URL.'],['3','Choose policy','Use one of three immutable policies. Users cannot inject custom prompts or thresholds.'],['4','Analyze','Sign the GenLayer write and wait for finalized consensus plus successful leader execution.'],['5','Read back','The UI loads the exact returned certificate state and its canonical call graph.'],['6','Interpret','CLEAR is scoped policy compliance only. REVIEW_REQUIRED, BLOCKED and UNRESOLVED are non-positive.']].map(x=><article key={x[0]}><i>{x[0]}</i><b>{x[1]}</b><p>{x[2]}</p></article>)}</div></section></main>
 <footer><span>{notice}</span><div>{ADDRESS?<a href={`${EX}/address/${ADDRESS}`} target="_blank">Contract {short(ADDRESS)} ↗</a>:<b>Deployment pending</b>}</div></footer></>}
createRoot(document.getElementById('root')).render(<App/>);
